### ISSUE TITLE
Broken graph when fetching for the first time

### ISSUE THREAD

**Issue by JeanMax** [JeanMax/babao#3]
```
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mc/babao/src/babao/graph.py", line 321, in initGraph
    raise e
  File "/home/mc/babao/src/babao/graph.py", line 315, in initGraph
    _getData()
  File "/home/mc/babao/src/babao/graph.py", line 103, in _getData
    since = lm.TRADES[crypto].current_row.name - du.secToNano(
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by JeanMax** [comment]
And you'll have this exception the second time if you still don't have "enough" data:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mc/babao/src/babao/graph.py", line 321, in initGraph
    raise e
  File "/home/mc/babao/src/babao/graph.py", line 316, in initGraph
    _initGraph()
  File "/home/mc/babao/src/babao/graph.py", line 233, in _initGraph
    lines = _createLines(axes)
  File "/home/mc/babao/src/babao/graph.py", line 185, in _createLines
    plt.setp(axes[key].get_xticklabels(), visible=key == "total-balance")
  File "/usr/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 3399, in get_xticklabels
    which=which))
  File "/usr/lib/python3.7/site-packages/matplotlib/axis.py", line 1296, in get_ticklabels
    return self.get_majorticklabels()
  File "/usr/lib/python3.7/site-packages/matplotlib/axis.py", line 1252, in get_majorticklabels
    ticks = self.get_major_ticks()
  File "/usr/lib/python3.7/site-packages/matplotlib/axis.py", line 1407, in get_major_ticks
    numticks = len(self.get_majorticklocs())
  File "/usr/lib/python3.7/site-packages/matplotlib/axis.py", line 1324, in get_majorticklocs
    return self.major.locator()
  File "/usr/lib/python3.7/site-packages/matplotlib/dates.py", line 1431, in __call__
    self.refresh()
  File "/usr/lib/python3.7/site-packages/matplotlib/dates.py", line 1451, in refresh
    dmin, dmax = self.viewlim_to_dt()
  File "/usr/lib/python3.7/site-packages/matplotlib/dates.py", line 1202, in viewlim_to_dt
    .format(vmin))
ValueError: view limit minimum -36688.65 is less than 1 and is an invalid Matplotlib date value. This often happens if you pass a non-datetime value to an axis that has datetime units
```
